# Generated by Django 5.2.6 on 2025-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_user_pfp_like_post_like_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
